### ISSUE TITLE
Default Messages

### ISSUE THREAD

**Issue by patrickml** [patrickml/votify#20]
When there is nothing in the queue we need some kind of default message this also goes for the search
- [ ] Default Queue Message
- [ ] No Results Found Message

**Comment by jangerhofer** [comment]
Especially on slower connections, the "Sorry, we don't have any songs for" is apparent even for what will shortly become valid searches.  At some point, let's set a loader/spinner until the response comes back from Spotify.  Not a big deal, just a finishing touch!
